### ISSUE TITLE
[question] how html version is generated

### ISSUE THREAD

**Issue by showgood** [tecosaur/emacs-config#1]
I really like the html version of the config file. I think it's different from the ReadTheOrg theme from  https://github.com/fniessen/org-html-themes.

Wonder if could share the theme and process how this html is generated from the org file?

Thanks!

**Comment by tecosaur** [comment]
As you have gleaned, this is indeed a tweaked version of https://github.com/fniessen/org-html-themes — I haven't done much though.

You can see the extra stuff in [config.html#exporting-html](https://tecosaur.github.io/emacs-config/config.html#exporting-html). Other than that, the export process is the exact same :smiley:
