### ISSUE TITLE
<TAB> not execute org-cycle when I opened config.org

### ISSUE THREAD

**Issue by atreeyang** [tecosaur/emacs-config#10]
when I opened "config.org" and press <TAB> on a org line, and give me a message "user-error: No matching item found on the current line"
It should execute org-cycle and expand the title. very inconvenient. shift-TAB is work anyway.

But when I open a simple org file, it execute org-cycle. Cant figure out why.

**Comment by tecosaur** [comment]
As it so happens, I'm aware of this issue (unlike the other issue you opened, I'll respond to that in a bit), but have no idea what's going on.

I'll let you know here if I make any progress :slightly_smiling_face:.

**Comment by tecosaur** [comment]
Related: https://github.com/hlissner/doom-emacs/issues/4548

**Comment by pnguyen4** [comment]
Hi. I was setting up doom emacs using this configuration as inspiration and I ran into the same problem with TAB not working. Commenting out `(add-hook! 'org-mode-hook #'+org-pretty-mode #'mixed-pitch-mode)` fixed the issue for me. I'm not sure why though.

**Comment by tecosaur** [comment]
Strange, thanks for letting me know. I'll test it out and see what I find.

By the way, do you also find this issue doesn't pop up with smaller files?

**Comment by pnguyen4** [comment]
No, this issue happens with small org files as well. I ran across it while following along Zaiste's Doomcast org mode tutorial. My configuration isn't literate.

**Comment by tecosaur** [comment]
Interesting to compare experiences. Just as @atreeyang mentioned, I only find this occurs with large Org files.

All I can guess at this point is that we're hitting some weird edge case :stuck_out_tongue:

**Comment by tecosaur** [comment]
Fixed in https://github.com/hlissner/doom-emacs/commit/16a495c97dd796ec20939d07bad3beb38586a1fe
