### ISSUE TITLE
[question] Generating text flowcharts

### ISSUE THREAD

**Issue by Gleek** [tecosaur/emacs-config#13]
Hi @tecosaur,
Thank you for publishing this.
I wonder how you generate the text flowcharts. They look really nice and I'm not aware of any tool that generate them this clean :).
I'm talking about these:
```

      ╭─╴Code╶─╮            ╭─╴Raw Code╶─▶ Computer
Ideas╺┥        ┝━▶ Org Mode╺┥
      ╰─╴Text╶─╯            ╰─╴Document╶─▶ People




                   ╭───────────────────────────────────▶ .pdf ⎫
                  pdfLaTeX ▶╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╮                 ⎪
                   ╿     ╿                  ┊                 ⎪
                   │     ┊                  ┊                 ⎪
                 .tex    ┊                  ┊                 ⎪
                   ╿     ┊                  ┊                 ⎪
                ╭──┴╌╌╮  ┊                  ┊ style.scss      ⎬ Weaving
graphc.png ─╮   │  embedded TeX             ┊      ╽          ⎪ (Documents)
image.jpeg ─┤ filters   ╿                   ┊    .css         ⎪
            ╎     ╿     ┊                   ┊     ▾╎          ⎪
figure.png╶─╧─▶ PROJECT.ORG ▶───╴filters╶───╧──────╪──▶ .html ⎪
     ╿           ╿┊ ║ │ ╰╌╌╌▷╌╌ embedded html ▶╌╌╌╌╯          ⎪
     ├╌╌╌╌╌╌╌▷╌╌╌╯┊ ║ │                                       ⎪
    result╶╌╌╌╌╌╮ ┊ ║ ├──────╴filters╶────────────────▶ .txt  ⎪
     ┊▴         ┊ ┊ ║ │                                       ⎪
    execution   ┊ ┊ ║ ╰──────╴filters╶────────────────▶ .md   ⎭
     ┊▴         ┊ ┊ ║
    code blocks◀╯ ┊ ╟─────────────────────────────────▶ .c    ⎫
     ╰╌╌╌╌◁╌╌╌╌╌╌╌╯ ╟─────────────────────────────────▶ .sh   ⎬ Tangling
                    ╟─────────────────────────────────▶ .hs   ⎪ (Code)
                    ╙─────────────────────────────────▶ .el   ⎭

```

I can't seem to find it in the rest of your config. I see you also have `graphviz-dot-mode` in your config but I'm not aware if that could be used to generate text. Is that what is used here? Looking forward for your response.

Thank you.

**Comment by tecosaur** [comment]
I'm glad you like them :slightly_smiling_face: I use a two-step process to generate them:
1. Open https://en.wikipedia.org/wiki/Box-drawing_character
2. Copy and paste

It would be nice if there was a tool for making them, but I'm not currently aware of any — sorry.

**Comment by Gleek** [comment]
Oh! interesting. Maybe modifying artist mode to add flowchart functionalities to it might be a way to go 😄.
As far as I'm aware, plantuml can generate text but uses simple keyboard characters and buggy when it comes to generating text, so it isn't  that clean.

**Comment by tecosaur** [comment]
I've thought that would be cool for a while, as you may guess though — I've got a lot that I'd like to do 😄.
