### ISSUE TITLE
weird unicode issue?

### ISSUE THREAD

**Issue by dangom** [tecosaur/emacs-config#15]
When looking at the HTML I see a weird missing symbol after clicking on a src code block, as seen on the left of the block on the image below:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/7881842/111785278-c6fcef80-8892-11eb-909c-eaf9f455d600.png">

Are there perhaps issues with the fonts?

**Comment by tecosaur** [comment]
Indeed, this character needs to come from a system font with decent unicode support.
This is what I see:
![image](https://user-images.githubusercontent.com/20903656/111789452-1cb9b200-88fc-11eb-8be0-35d396f1e5e7.png)

**Comment by dangom** [comment]
yes, I suppose my system doesn't have those. If I may ask another question, is there an easy way to deactivate unicode characters in your export functions? The export looks really nice. I've been testing them out on some of my org reports, yet the missing fonts on my system make it seem as if something important is missing or broken.

**Comment by tecosaur** [comment]
If you've copied over the relevant parts to your config to have your export be a bit like mine, you can just edit the characters used to be ones present on your system. Try `M-x occur [^[:ascii:]] RET`.
