### ISSUE TITLE
mu4e filenotify (rebuild mail index while using mu4e) on Mac OS

### ISSUE THREAD

**Issue by yevhenshymotiuk** [tecosaur/emacs-config#16]
I'm trying to make your mu4e config (at least fetching and reindexing) work on Mac OS. I think, everything will work, if substitute systemd-related code with launchd one in your python script `mbsync-imapnotify.py`. Currently I use this script just to parse my config. While testing after adding lisp code, i found out, that `(file-notify-add-watch mu4e-reindex-request-file '(change) #'mu4e-file-reindex-request)` will not work as expected, because I cant add watcher, if `mu4e-reindex-request-file` does not exist. I suppose it is specific to the library, which is used by `filenotify` on Mac OS, or it is specific to the filesystem itself. So, if you have any ideas, I will be very thankful

**Comment by tecosaur** [comment]
Hey! Somehow this slipped past, but I'll see if I can still be of some helf:
1. The OS library probably likely make a difference
2. The location of the temp file (previously hardcoded to `/tmp`) could have been problematic for Mac, however this has recently been changed so this might improve things

Good luck! :smiley:
