### ISSUE TITLE
M-x ediff-files hangs emacs with high CPU utilizaiton

### ISSUE THREAD

**Issue by yubrshen** [tecosaur/emacs-config#18]
First, thanks for producing a very elegant doom emacs-config, well documented!
When I performed ediff between two files, after providing file B, the emacs hanged, without displaying the ediff buffers, but the status area shows "processing difference regions ... done".

The emacs process has to be aborted through task manager. C-g would not work, neither SPC q

The emacs version is Emacs 27.1 
I running emacs not as a daemon, just an application by:
emacs & # at command line or 
~/.emacs.d/ibn/doom run &

The computer environment is Ubuntu 18.04 in WSL 1 in Windows 10.
could this be the source of the problem?

Here is a screenshot showing where it hanged and the high CPU utilization of  the emacs process.
![image](https://user-images.githubusercontent.com/2638417/122454243-05707c00-cf60-11eb-8bb7-93c39339811d.png)

I tried ediff-buffers has the same problem.

**Comment by tecosaur** [comment]
Very curious. While I don't use ediff a lot, I do use it, and have yet to see an issue like this with it...

**Comment by yubrshen** [comment]
I've isolated further. By only keeping the rudimentary configuration, with some further stripping down the packages, and have empty packages.el then the problem was gone. I'll monitor and add more as needed to see where it breaks.

**Comment by tecosaur** [comment]
I'll close this for now, but feel free to re-open if you get any more information :slightly_smiling_face:

**Comment by yubrshen** [comment]
OK.
I've been using your minimum configuration and cautiously adding some
customization for org mode, etc.
So far, so good.

Thanks!

Yu (Aaron)

J'ecrite, donc je pense.
Je pense, donc je suis.
