### ISSUE TITLE
keycast issue

### ISSUE THREAD

**Issue by bdarcus** [tecosaur/emacs-config#19]
I was looking to borrow your keycast config, but get this error when running `keycast-mode`.

``` console
user-error: Cannot turn on keycast-mode.  mode-line-buffer-identification not found in mode-line-format. 
```

Any ideas?

**Comment by tecosaur** [comment]
I just tested this and it's working for me, so given that I don't mention `mode-line-buffer-identification` in my config, I'm guessing this is either related to:
-  Me using `Emacs28`
- My Doom packages

In future, I think it could be nice to add some unit tests for various bits of functionality to my CI.

**Comment by bdarcus** [comment]
I had been using `Emacs28` for a long time, but downgraded for some reason. Upgrading again gives the same error though.

The sentence after the message I quoted says the following, so maybe I'll look into that.

``` console
Try customizing keycast-insert-after.
```

**Comment by tecosaur** [comment]
Hmm, as I read it those steps should be performed in my config.

**Comment by bdarcus** [comment]
Right.

I've been having random issues in my install for a couple weeks, so probably just something local to me.

Sigh.

**Comment by tecosaur** [comment]
I know the feeling :cry:. Good luck!
