### ISSUE TITLE
Whether the install script can be installed in macos?

### ISSUE THREAD

**Issue by YukoOshima** [tecosaur/emacs-config#20]
I run the install script in macOS and the emacs can not run properly. Whether it can be installed in macOS?

**Comment by tecosaur** [comment]
My priority with this config is making a nice config for me :stuck_out_tongue: and I only run Linux.

It's also explicitly *not* meant to be copied wholesale, see https://tecosaur.github.io/emacs-config/config.html#notes-unwary-adventurer

It probably wouldn't take too much effort to get things working in MacOS, but I can't say I have any interest in looking into it.
