### ISSUE TITLE
Org-capture Issue in your config.

### ISSUE THREAD

**Issue by prashantnag93** [tecosaur/emacs-config#22]
I have found one issue in your config and [report it here (https://github.com/progfolio/doct/issues/28)].
Even after the issue is resolved but `+org-capture-project-todo-file` function is not able to find the right file for todo.

**Comment by tecosaur** [comment]
If `+org-capture-project-todo-file` is misbehaving, see

https://github.com/hlissner/doom-emacs/blob/8b3b39532d82261c5d4581bab421c4328ffa0db1/modules/lang/org/autoload/org-capture.el#L97

as this functions is not affected by my config.
