### ISSUE TITLE
Errors from init hooks

### ISSUE THREAD

**Issue by emadbaqeri** [tecosaur/emacs-config#26]
Hey there, I have tried to install the configuration according to the instructions on the `README.md` file, but this is the outcome.
What should I have done about this 😕 
![Screenshot from 2021-12-10 02-39-50](https://user-images.githubusercontent.com/50639499/145490345-4fbf3e59-5068-4efd-b901-af30e7a099bb.png)

**Comment by donneyluck** [comment]
the same error

**Comment by emadbaqeri** [comment]
Hey @donneyluck, thank you, I have already done that but there is still some other errors after applying these changes, but let me do that again and see the outcome, that you really much

**Comment by tecosaur** [comment]
Occasionally there are a few committed bits. My earlier comments on copying my config wholesale stand, I strongly recommend *not* doing that.
