### ISSUE TITLE
the search project not work

### ISSUE THREAD

**Issue by donneyluck** [tecosaur/emacs-config#27]
Press SPC /  

![](https://emacs-china.org/uploads/default/original/3X/e/d/ed2b4fc46b21ca06e035ac9d1088dbd519c9486e.png)

![](https://emacs-china.org/uploads/default/original/3X/b/f/bf528753f6480e4c29d7edc508b2b2a9e5293a2d.png)

**Comment by emadbaqeri** [comment]
Hey @donneyluck, I think the problem is you are have `ripgrep` installed on you machine.
In my case as I'm using Ubuntu I just simply tried `sudo apt install ripgrep` that works for me.

**Comment by tecosaur** [comment]
See https://tecosaur.github.io/emacs-config/config.html#consult, I think `(setf (plist-get (alist-get 'perl consult-async-split-styles-alist) :initial) ";")` may not work on non-recent versions of Emacs.
