### ISSUE TITLE
Teach-a-man-to-fish example will not run.

### ISSUE THREAD

**Issue by JohnNehls** [tecosaur/emacs-config#28]
In your excellent config.org, the example command 
```
(defadvice! prompt-for-buffer (&rest _)
      :after 'window-split (switch-to-buffer))
```
yields "progn: Symbol’s function definition is void: defadvice!" in vanilla emacs.

**Comment by tecosaur** [comment]
Yes, that example uses Doom. I don't think that affects the overall point though.
