### ISSUE TITLE
Translate into Persian 🇮🇷 

### ISSUE THREAD

**Issue by mmdbalkhi** [tecosaur/emacs-config#29]
# Translate into Persian 🇮🇷 

Hello. I can translate this text into Persian
I think I should translate the two files `readme.org` and` conf.org`, Do you need to do anything other than that?
And one question, How do I export these files?

## TODO:

- [ ] Translate `readme.org`
- [ ] Translate `conf.org`

**Comment by tecosaur** [comment]
While I appreciate the interest you have, this would be a massive undertaking that would need to be kept in sync with the changes I make. If you think some particular bits could be helpful to others, feel free to translate them and post them somewhere, but while I admire your enthusiasm this seems like going a bit too far.

**Comment by mmdbalkhi** [comment]
Thank you for your importance to this issue. I built a repo and I try to do things there and I try to be relatively up-to-date. thanks for your attention
