### ISSUE TITLE
How do you handle qwerty-oriented keybindings?

### ISSUE THREAD

**Issue by PlaneTraveller** [tecosaur/emacs-config#30]
Thanks for the effort to make your config literate! For an emacs noob like me, it has been an insanely helpful example! 
How did you handle qwerty-based keybindings?(evil movement keys, movement keys in other modes, etc) I'm a colemak user struggling to make movement work for colemak globally. Since you mentioned in your config that you're a colemak user as well, I thought I'd ask.

**Comment by tecosaur** [comment]
I just use the same keys anyway. Other than hjkl, most of vim's keybindings are mnemonic-based (e.g. `f` for forwards, etc.) rather than layout-based and I've found the experience fine :slightly_smiling_face: The one customisation I have done is with `avy-keys`.

**Comment by PlaneTraveller** [comment]
thx!
