### ISSUE TITLE
Splash screen script changes color of cursor to default (black)

### ISSUE THREAD

**Issue by donCESAR12345** [tecosaur/emacs-config#33]
So, I tried just copying the splash screen code (because it looks so damn good), took the svg too, but my cursor is getting black with that code, couldn't figure out where is the function that does this, and it kinda annoys me because I use a dark theme and getting a black cursor is not optimal for my not so good eyes.

Default theme cursor without loading splash screen
![Default theme cursor without loading splash screen](https://i.imgur.com/1EOrsKg.png)

Black cursor after loading splash screen
![Black cursor after loading splash screen](https://i.imgur.com/NQFdozp.png)

Would love some help. xoxo.

**Comment by tecosaur** [comment]
If you could provide a step-by-step description of how to reproduce this, that would be helpful.
