### ISSUE TITLE
doom sync taking too long

### ISSUE THREAD

**Issue by sasinhe** [tecosaur/emacs-config#36]
Hi!
I've noticed that after installing your config (all of it) my doom sync is taking too long (around 1 minute).
Is that expected? Maybe it's reinstalling some stuff...

**Comment by tecosaur** [comment]
I see that you've decided to ignore the warning https://tecosaur.github.io/emacs-config/config.html#notes-unwary-adventurer. Unfortunately, this is something you'll have to figure out yourself.
