### ISSUE TITLE
Unexpected error after CLI:Initializing recipes

### ISSUE THREAD

**Issue by JxJxxJxJ** [tecosaur/emacs-config#38]
May I ask for help to find where does this come from please? What confuses me the most is the mention of (stringp afternoon-theme). Just in case I installed afternoon but nothing really changed. 

I'm using pieces of the config.org in the repo, everything works fine but this, I can't =SPC h r r=, this is what it says: 
[cli.doom.221125034355.2690362.log](https://github.com/tecosaur/emacs-config/files/10089262/cli.doom.221125034355.2690362.log)

**Comment by JxJxxJxJ** [comment]
Here's the config.org that is copied down so far

[config.txt](https://github.com/tecosaur/emacs-config/files/10089281/config.txt)

(rename it to config.org to see properly, changed it to txt so I can upload it here)

**Comment by MormonJesus69420** [comment]
This issue is not related to Teco's config or Doom, it's an issue with straight. Here's a quick workaround for now
https://github.com/doomemacs/doomemacs/issues/6960#issuecomment-1327102249
