### ISSUE TITLE
org-return-indent is obsolete and breaks org-return-dwim

### ISSUE THREAD

**Issue by treitmaier** [tecosaur/emacs-config#4]
First of all, thank you for documenting your config so thoroughly here. One of the things I copied from your config is the `org-return-dwim` function. Or more specifically, how you use it by advising the `org-return-indent` function. Until I saw your approach, I was never able to get the `org-return-dwim` function to map to RET in doom.

Unfortunately, the org-return-indent command is obsolete since Org 9.4. And this breaks the `org-return-dwim` configuration. Any chance you can have a look at if it still works for you?

**Comment by tecosaur** [comment]
Thanks for opening this issue. I have noticed issues with `org-return-dwim` no longer working for me.
Unfortunately, I just haven't had time to look into it yet.

If you are interested in trying to get this working again, please let me know if you know if you find a solution to this :smiley:

**Comment by treitmaier** [comment]
Thanks for responding so quickly and confirming you're facing the same issue. After trying various permutations of `:after org/evil-org` and `:map org-mode-map/evil-org-mode-map`, the following snippet finally got the binding to stick.

```
(map!
 :after evil-org
 :map evil-org-mode-map
 :i [return] #'unpackaged/org-return-dwim)
```

Hope it works for you too!

**Comment by tecosaur** [comment]
It does! Thanks for sorting this out.
