### ISSUE TITLE
(unpin! org) (package! org-contrib) recipe error 

### ISSUE THREAD

**Issue by JxJxxJxJ** [tecosaur/emacs-config#40]
This snippet at Language Configuration -> Packages -> Org itself 

> #+begin_src emacs-lisp :tangle packages.el :noweb no-export
> <<org-pkg-statement()>>
> (unpin! org) ; there be bugs
> (package! org-contrib
>   :recipe (:host nil :repo "https://git.sr.ht/~bzg/org-contrib"
>            :files ("lisp/*.el"))
>   :pin "6422b265f1150204f024e33d54f2dcfd8323005c")
> #+end_src

Causes the following error after tangling and reloading doom: https://pastebin.com/vi0WeVwY

Deleting it lets you be able to reload the config successfuly afterwards

**Comment by tecosaur** [comment]
Known issue, an unpushed fix is in the works.
