### ISSUE TITLE
Modeline cut off in only org-files.

### ISSUE THREAD

**Issue by JxJxxJxJ** [tecosaur/emacs-config#43]
As you can see the time weirdly gets cut off 
![image](https://user-images.githubusercontent.com/103049321/204520327-312926f2-e069-45f0-afd1-fcddab17f6e8.png)
This does not happen with other type of files (such as, `.pdf`, `.tex`, `.txt`) here is a `.txt` example: in this case it looks perfect. 
![image](https://user-images.githubusercontent.com/103049321/204520617-0c84153f-2dd5-4f40-a666-47eeeaff7da7.png)

I've tried this but didn't help. 

https://github.com/doomemacs/doomemacs/blob/develop/modules/ui/modeline/README.org#the-right-side-of-the-modeline-is-cut-off

Can you replicate it?

**Comment by tecosaur** [comment]
I can replicate a milder version, but this is really a doom-modeline issue.

**Comment by JxJxxJxJ** [comment]
Good to know, thanks :slightly_smiling_face: .

**Comment by JxJxxJxJ** [comment]
Just to confirm, the proposed fixes at https://github.com/seagle0128/doom-modeline#faq point 7 did not work for you either?

**Comment by JxJxxJxJ** [comment]
Deleting the whole `Packages -> Visuals` module fixed it. Will keep bisecting that

**Comment by JxJxxJxJ** [comment]
Commenting out `Packages -> Visuals -> Mixed pitch -> Variable pitch serif font` solves it 
![image](https://user-images.githubusercontent.com/103049321/204660443-c6048315-fead-48a9-a864-36a076ed8832.png)
Even though if you leave `Packages -> Visuals -> Mixed pitch` it throws some errors for fonts ant writeroom doesn't have mixed pitch 
![image](https://user-images.githubusercontent.com/103049321/204661191-a5753f1d-6fd0-4437-a312-88f832f27ba2.png)
![image](https://user-images.githubusercontent.com/103049321/204661261-224065b5-82a4-4c24-8d9a-4b50ab32ab36.png)

**Comment by JxJxxJxJ** [comment]
Would there be any way to maintain mixed pitch in writeroom **and** fix the time? :disappointed:
