### ISSUE TITLE
LSP support in src blocks

### ISSUE THREAD

**Issue by wuqui** [tecosaur/emacs-config#5]
Thanks for sharing your awesome config!

I'm very interested in getting LSP to play nicely with org source blocks, and I've only had limited success so far. I saw you have a section in your config on that topic. Unfortunately, I don't know what it does exactly and how to get it running. Could you elaborate? Would be much appreciated.

**Comment by tecosaur** [comment]
You should be able to just copy that block into your config. The way it should work is by creating a temporary file for the LSP server to be called on, linking it to the buffer, and starting LSP up. It's not my own code (credit to [@seagle0128](https://github.com/seagle0128/.emacs.d/blob/7c3c58150d400776c5261a34205d4bc3f8fc59a2/lisp/init-lsp.el#L430)), but it's worked fairly well for me :)

**Comment by wuqui** [comment]
Thanks for explaining. Doesn't work for me, unfortunately. Does it something similar to `lsp-org` from `lsp-mode` or is that something you use additionally?

**Comment by tecosaur** [comment]
Unfortunately, yea. Not sure how well `lsp-org` works, it wasn't around when I started using this.

**Comment by wuqui** [comment]
I have now switched from using LSP to just using `anaconda-mode` in the org file. I'm using `emacs-jupyter` and I'm evaluating stuff from the org buffer using `C-x C-e`, so I don't even have to rely on `org-edit-special` buffers anymore. This is a great setup for me now, just to let you know in case you're interested. I haven't found this anybody else suggesting this, to my surprise. And thanks anyways.
