### ISSUE TITLE
I don't think `cargo-script` runs rust blocks by babel?

### ISSUE THREAD

**Issue by 0atman** [tecosaur/emacs-config#6]
Hi @tecosaur! Thanks for publishing your emacs config, this is a fantastic resource for newbies like me! :pray: 

However, I don't think this statement is correct:
> The cargo-script rust crate is required for evaluation of rust blocks by babel.
https://github.com/tecosaur/emacs-config/master/config.org#L266

I don't see `cargo script` or `ob-rust` used in any of your config:

```md
λ ack ob-rust
config.html
3469:As described in the <span class='acr'>README</span> for <a href="https://github.com/micanzhang/ob-rust">ob-rust</a>. Like <code>delta</code>, this can just be installed

config.org
267:  As described in the README for [[https://github.com/micanzhang/ob-rust][ob-rust]]. Like ~delta~, this can just be installed

λ ack cargo-script
config.html
3468:The <kbd>cargo-script</kbd> rust crate is required for evaluation of rust blocks by babel.
3477:<pre class="src src-shell">cargo install cargo-script

config.org
266:+ The =cargo-script= rust crate is required for evaluation of rust blocks by babel.
269:  #+begin_src shell :eval no :tangle (if (executable-find "cargo-script") "no" "setup.sh")
270:cargo install cargo-script
```

I REALLY WANT to be able to run rust blocks using `cargo-script`! It'd be so great to be able to use crates in org src blocks. So if you know how to do this, I'd be very grateful if you update your documentation or let me know :grin:

**Comment by tecosaur** [comment]
Ah, I was thinking of https://github.com/micanzhang/ob-rust, but turns out it's actually https://github.com/brotzeit/rustic#org-babel that's used — so that's redundant. Thanks for pointing this out.

**Comment by 0atman** [comment]
omg YES! Thank you, I am LOVING rustic babel!
