### ISSUE TITLE
where to use "use-package :after

### ISSUE THREAD

**Issue by laurentHYZ** [tecosaur/emacs-config#7]
Hi Tecosaur, 
I am trying of learn from your config file, thank you for sharing info and explanations it helps a lot.
So I am trying to install some of the packages you have in your doomdir. 
For ex I tried to install org-pandoc-import, I synced succesfully, but I can not find it on M-x.
I guess I should execute the (use-package org-pandoc-import :after or) but I don't know in which file I am supposed to write that (use-package)thingy, 
thank you!

`(use-package org-roam-server
  :after (org-roam server)
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8078
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20)
  (defun org-roam-server-open ()
    "Ensure the server is active, then open the roam graph."
    (interactive)
    (org-roam-server-mode 1)
    (browse-url-xdg-open (format "http://localhost:%d" org-roam-server-port))))`

**Comment by tecosaur** [comment]
Hi Laurent,

If you want `org-pandoc-import`, I'd take a look at the readme for the package: https://github.com/tecosaur/org-pandoc-import.

**Comment by laurentHYZ** [comment]
thank you!
I have a question about your config.org:
is it the place where you actually write your configuration, and you just tangle blocks to their final destination?
If that is the case could you  explain me the following code-block?
#+begin_src emacs-lisp :tangle yes
(use-package! org-pandoc-import
  :after org)
#+end_src

You are using the :tangle, but I don't understand why there is no destination file for the tangling, as I was under the impression that using :tangle would only work if we specify the destination file we want to write to

**Comment by tecosaur** [comment]
If in `foo.org` you have a python block with `:tangle yes` it will tangle to `foo.py`, etc.
