### ISSUE TITLE
wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by atreeyang** [tecosaur/emacs-config#9]
followed is my Message buffer, when I start emacs with emacs --debug-init
======================
DOOM Initializing Doom
Debug mode on
DOOM Initializing core modules
DOOM Initializing user config
DOOM Running doom hook: evil-mode
DOOM Running doom hook: +evil--init-popup-rules-h
DOOM Running doom hook: +workspaces-init-h
Power Battery, battery high (90% load, remaining time 4:56)
DOOM [editor/evil] Initialized evil-collection-elisp-mode (too early!)
DOOM [editor/evil] Initialized evil-collection-comint (too early!)
DOOM [editor/evil] Initialized evil-collection-custom (too early!)
DOOM Running doom hook: +doom-dashboard-init-h
Error during redisplay: (eval (if (s-contains-p org-roam-directory (or buffer-file-name "")) (replace-regexp-in-string ".*/[0-9]*-?" "☰ " (subst-char-in-string 95 32 buffer-file-name)) "%b")) signaled (wrong-type-argument stringp nil)
DOOM [editor/evil] Initialized evil-collection-ibuffer (too early!)
DOOM [editor/evil] Initialized evil-collection-compile (too early!)
DOOM [editor/evil] Initialized evil-collection-grep (too early!)
Error during redisplay: (eval (if (s-contains-p org-roam-directory (or buffer-file-name "")) (replace-regexp-in-string ".*/[0-9]*-?" "☰ " (subst-char-in-string 95 32 buffer-file-name)) "%b")) signaled (wrong-type-argument stringp nil) [3 times]
DOOM [ui/doom-dashboard] Reloading dashboard at 14:49:22

**Comment by tecosaur** [comment]
Hmmm, I thought this was trivial but it shouldn't have this error as long as `org-roam-directory` is defined. Do you have any more information?

**Comment by tecosaur** [comment]
Feel free to reopen if you have any more info.
